-- Baseline schema for the "prod" (Postgres) profile.
--
-- This is a direct transcription of the DDL Hibernate generates today from
-- the JPA entities under com.eduardo.rpg (captured by running the app with
-- the "local"/H2 profile, ddl-auto: update, and reading the "create table"
-- statements Hibernate logs on startup), adapted to Postgres syntax:
--   * H2's native inline "enum (...)" column type has no Postgres
--     equivalent for a plain @Enumerated(EnumType.STRING) mapping -- it
--     becomes a VARCHAR(n) column instead (matching the @Column(length=...)
--     declared on each enum field), same as what Hibernate itself would
--     generate against a Postgres dialect.
--   * "bigint generated by default as identity" is valid Postgres syntax
--     as-is (identity columns, PG10+) and was kept unchanged.
--
-- Going forward, schema changes belong in new Vn__*.sql files, never in
-- edits to this one -- ddl-auto is "validate" in prod (see
-- application-prod.yml), so Flyway is the only thing allowed to change the
-- prod schema.

create table tb_abilities (
    id bigint generated by default as identity,
    campaign_id bigint,
    cost varchar(200),
    cost_type varchar(50),
    created_at timestamp(6) not null,
    damage varchar(50),
    description varchar(1000),
    effect varchar(500),
    main_status varchar(100),
    name varchar(150) not null,
    required_level integer,
    updated_at timestamp(6) not null,
    primary key (id)
);

create table tb_ability_requirements (
    id bigint generated by default as identity,
    min_charisma integer,
    min_constitution integer,
    min_dexterity integer,
    min_intelligence integer,
    min_level integer,
    min_strength integer,
    min_wisdom integer,
    ability_id bigint not null,
    class_id bigint not null,
    primary key (id)
);

create table tb_campaign_players (
    campaign_id bigint not null,
    player_id bigint not null
);

create table tb_campaigns (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    description varchar(500),
    invite_code varchar(20) not null,
    name varchar(100) not null,
    status boolean not null,
    updated_at timestamp(6) not null,
    master_id bigint not null,
    primary key (id)
);

create table tb_character_abilities (
    character_id bigint not null,
    ability_id bigint not null
);

create table tb_character_equipments (
    character_id bigint not null,
    equipment_id bigint not null
);

create table tb_character_statuses (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    current_value integer not null,
    updated_at timestamp(6) not null,
    character_id bigint not null,
    template_id bigint not null,
    primary key (id)
);

create table tb_characters (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    description varchar(500),
    experience integer not null,
    gender varchar(30) not null,
    level integer not null,
    name varchar(100) not null,
    character_role varchar(20) not null,
    updated_at timestamp(6) not null,
    campaign_id bigint,
    class_id bigint not null,
    race_id bigint not null,
    user_id bigint not null,
    primary key (id)
);

create table tb_class_abilities (
    class_id bigint not null,
    ability_id bigint not null
);

create table tb_classes (
    id bigint generated by default as identity,
    campaign_id bigint,
    charisma_bonus integer not null,
    constitution_bonus integer not null,
    created_at timestamp(6) not null,
    description varchar(1000),
    dexterity_bonus integer not null,
    intelligence_bonus integer not null,
    name varchar(100) not null,
    strength_bonus integer not null,
    updated_at timestamp(6) not null,
    wisdom_bonus integer not null,
    primary key (id)
);

create table tb_equipment_requirements (
    id bigint generated by default as identity,
    min_charisma integer,
    min_constitution integer,
    min_dexterity integer,
    min_intelligence integer,
    min_strength integer,
    min_wisdom integer,
    equipment_id bigint not null,
    class_id bigint not null,
    primary key (id)
);

create table tb_equipments (
    id bigint generated by default as identity,
    campaign_id bigint,
    charisma_bonus integer not null,
    constitution_bonus integer not null,
    created_at timestamp(6) not null,
    damage varchar(50),
    description varchar(1000),
    dexterity_bonus integer not null,
    intelligence_bonus integer not null,
    name varchar(150) not null,
    strength_bonus integer not null,
    equipment_type varchar(30) not null,
    updated_at timestamp(6) not null,
    wisdom_bonus integer not null,
    primary key (id)
);

create table tb_races (
    id bigint generated by default as identity,
    campaign_id bigint,
    charisma_bonus integer not null,
    constitution_bonus integer not null,
    created_at timestamp(6) not null,
    description varchar(1000),
    dexterity_bonus integer not null,
    intelligence_bonus integer not null,
    name varchar(100) not null,
    strength_bonus integer not null,
    updated_at timestamp(6) not null,
    wisdom_bonus integer not null,
    primary key (id)
);

create table tb_session_characters (
    session_id bigint not null,
    character_id bigint not null
);

create table tb_sessions (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    notes varchar(1000),
    story varchar(2000) not null,
    title varchar(120) not null,
    updated_at timestamp(6) not null,
    campaign_id bigint not null,
    primary key (id)
);

create table tb_status_templates (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    default_value integer not null,
    description varchar(1000),
    max_value integer,
    min_value integer,
    name varchar(100) not null,
    updated_at timestamp(6) not null,
    campaign_id bigint not null,
    primary key (id)
);

create table tb_users (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    email varchar(100) not null,
    password varchar(255) not null,
    role varchar(20) not null,
    updated_at timestamp(6) not null,
    username varchar(50) not null,
    primary key (id)
);

alter table tb_campaigns add constraint UKbii97xa6sgg8x35nghk02jv6c unique (invite_code);
alter table tb_character_statuses add constraint UKm9unpw1llp57v1mk3vvkqh615 unique (character_id, template_id);
alter table tb_classes add constraint UK8urjn3w4ar72cnsgn8xt2ldbx unique (name);
alter table tb_races add constraint UK5brexjgy5l9o1twgavconuaej unique (name);
alter table tb_status_templates add constraint UKs9mu9ohopn958e8ylkde3ldcq unique (campaign_id, name);
alter table tb_users add constraint UKgrd22228p1miaivbn9yg178pm unique (email);
alter table tb_users add constraint UK8n82lwp7lflhwda2v2v3wckc9 unique (username);

alter table tb_ability_requirements add constraint FKiroecc3s28tatevwmwqjawfkv foreign key (ability_id) references tb_abilities;
alter table tb_ability_requirements add constraint FKdvkt3gdrf8est9lnlr0uh8op0 foreign key (class_id) references tb_classes;
alter table tb_campaign_players add constraint FK979esotp6kph5207fiv5k58eb foreign key (player_id) references tb_users;
alter table tb_campaign_players add constraint FK5xy7a2rqmexeajv4bfvs8epuf foreign key (campaign_id) references tb_campaigns;
alter table tb_campaigns add constraint FK8a2jgp5aqtidssbutegdiqll9 foreign key (master_id) references tb_users;
alter table tb_character_abilities add constraint FK230ae8li0o1mr75fygo4sxp1q foreign key (ability_id) references tb_abilities;
alter table tb_character_abilities add constraint FKrauem3v09j9pdhtnhtv42phbi foreign key (character_id) references tb_characters;
alter table tb_character_equipments add constraint FK8ty5v3uj3wtqo5qpd4a1y5pc5 foreign key (equipment_id) references tb_equipments;
alter table tb_character_equipments add constraint FK425hybb1bs7uhkk8y9asjugd2 foreign key (character_id) references tb_characters;
alter table tb_character_statuses add constraint FKafj6gttgym0askv928npf3oc5 foreign key (character_id) references tb_characters;
alter table tb_character_statuses add constraint FK8q9x490d3w3v4sw14g987gcus foreign key (template_id) references tb_status_templates;
alter table tb_characters add constraint FKp64k5omym95unlriy0f71618a foreign key (campaign_id) references tb_campaigns;
alter table tb_characters add constraint FKd5tnlx615d5vw6dclrivv1350 foreign key (class_id) references tb_classes;
alter table tb_characters add constraint FKnb15rer7597ktqfh14x1u5cc foreign key (race_id) references tb_races;
alter table tb_characters add constraint FKa9rpgjv6u03w8rf5dk8uu2xtm foreign key (user_id) references tb_users;
alter table tb_class_abilities add constraint FK216w5ctgye7w694p6ntfsjiwu foreign key (ability_id) references tb_abilities;
alter table tb_class_abilities add constraint FKgjcou2ewrnu1s76y0p9mpu5h7 foreign key (class_id) references tb_classes;
alter table tb_equipment_requirements add constraint FKh6xufwulvaqlyyfnxfy744xyy foreign key (equipment_id) references tb_equipments;
alter table tb_equipment_requirements add constraint FK6wbdmvmdmyguw2c81b2g95pec foreign key (class_id) references tb_classes;
alter table tb_session_characters add constraint FKaoham17cdm82gdo5jfthb1kv8 foreign key (character_id) references tb_characters;
alter table tb_session_characters add constraint FK6s67wcirc092mono147lcuu3o foreign key (session_id) references tb_sessions;
alter table tb_sessions add constraint FK6f91gofm12wvcd0pkjt3us8m1 foreign key (campaign_id) references tb_campaigns;
alter table tb_status_templates add constraint FKpnuexgigspplw44ejuu0u289v foreign key (campaign_id) references tb_campaigns;
