-- Additive migration: combat grid (per-session battle map) + notes/handouts
-- (campaign-wide or session-scoped). Matches the JPA entities under
-- com.eduardo.rpg.Grid and com.eduardo.rpg.Note exactly (verified against
-- Hibernate's generated DDL on the local/H2 profile with ddl-auto: create).

create table tb_combat_grids (
    id bigint generated by default as identity,
    cols integer not null,
    created_at timestamp(6) not null,
    rows integer not null,
    updated_at timestamp(6) not null,
    session_id bigint not null,
    primary key (id)
);

create table tb_grid_tokens (
    id bigint generated by default as identity,
    color varchar(20),
    created_at timestamp(6) not null,
    label varchar(100) not null,
    updated_at timestamp(6) not null,
    x integer not null,
    y integer not null,
    character_id bigint,
    grid_id bigint not null,
    primary key (id)
);

create table tb_notes (
    id bigint generated by default as identity,
    content text not null,
    created_at timestamp(6) not null,
    title varchar(150) not null,
    updated_at timestamp(6) not null,
    campaign_id bigint not null,
    session_id bigint,
    primary key (id)
);

alter table tb_combat_grids add constraint uk_combat_grids_session_id unique (session_id);

alter table tb_combat_grids add constraint fk_combat_grids_session foreign key (session_id) references tb_sessions;
alter table tb_grid_tokens add constraint fk_grid_tokens_grid foreign key (grid_id) references tb_combat_grids;
alter table tb_grid_tokens add constraint fk_grid_tokens_character foreign key (character_id) references tb_characters;
alter table tb_notes add constraint fk_notes_campaign foreign key (campaign_id) references tb_campaigns;
alter table tb_notes add constraint fk_notes_session foreign key (session_id) references tb_sessions;
